[pytest]
python_files = test_*.py *_test.py
python_functions = test_*
python_classes = Test*

markers =
    smoke: Смоук тесты
    regression: Регрессионные тесты
    users: Тесты касающиеся возможностей пользователя
    authentication: Тесты механизма аутентификации
    file: Тесты работы с файлами
    courses: Тесты связанные с курсами
    exercises: Тесты связанные с упражнениями курсов

addopts = -s -v
